# Generated by Django 6.0.4 on 2026-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_remove_vote_receipt_id_alter_vote_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='platform',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
