# Generated by Django 6.0.4 on 2026-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_candidate_achievements_candidate_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='year_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
