# Generated by Django 6.0.4 on 2026-05-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_candidate_course_candidate_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='partylist',
        ),
        migrations.CreateModel(
            name='PartyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='party_logos/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='election.election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='election.partylist'),
        ),
    ]
